### ISSUE TITLE
Improve metadata filter in example

### ISSUE THREAD

**Issue by NormandErwan** [NormandErwan/DocFxForUnity#8]
`Documentation/filterConfig.yml`:
```yaml
apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
```
